# Generated by Django 3.1.4 on 2020-12-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pki_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=30)),
                ('vendor', models.CharField(choices=[('huawei', 'huawei'), ('ericsson', 'ericsson')], max_length=30, null=True)),
                ('serial', models.CharField(max_length=30)),
                ('activity', models.CharField(max_length=30)),
                ('region', models.CharField(choices=[('Alex', 'Alex'), ('Cairo', 'Cairo'), ('Delta', 'Delta'), ('Giza', 'Giza'), ('Upper', 'Upper'), ('L1', 'L1')], max_length=30, null=True)),
                ('function', models.CharField(choices=[('Imp', 'Imp'), ('Rollout', 'Rollout'), ('IBS', 'IBS'), ('L1', 'L1')], max_length=30, null=True)),
                ('pki_status1', models.CharField(blank=True, choices=[('Exists', 'Exists'), ('Request_in_progress', 'Request In-Progress'), ('Requested', 'Requested')], default='Requested', max_length=30, null=True)),
                ('pki_status2', models.CharField(blank=True, choices=[('Removed', 'Removed'), ('Exists', 'Exist')], max_length=30, null=True)),
                ('crq_status', models.CharField(blank=True, choices=[('Need CRQ', 'Need CRQ'), ('RFA', 'RFA'), ('Done', 'Done')], max_length=30, null=True)),
                ('crq_no', models.CharField(blank=True, max_length=30)),
                ('batch_no', models.IntegerField(default=0)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('admin_export_date', models.DateField(blank=True, null=True)),
                ('crq_creation_date', models.DateField(blank=True, null=True)),
                ('crq_executation_date', models.DateField(blank=True, null=True)),
                ('export_collect', models.IntegerField(default=0)),
                ('create_export', models.IntegerField(default=0)),
                ('execute_create', models.IntegerField(default=0)),
                ('total_issue_time', models.IntegerField(default=0)),
                ('pki_comment', models.TextField(blank=True, null=True)),
                ('req_type', models.CharField(blank=True, choices=[('Add', 'Add'), ('Remove', 'Remove')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pki_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serials', models.CharField(max_length=30)),
                ('vendor', models.CharField(max_length=30)),
            ],
        ),
    ]
