# Generated by Django 3.1.4 on 2020-12-30 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import technical_plan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tp_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_name', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=technical_plan.models.current_year)),
                ('fy_year', models.CharField(max_length=7, null=True)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tp_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stream', models.CharField(max_length=30, null=True)),
                ('Alex_ER', models.IntegerField(default=0)),
                ('Alex_HU', models.IntegerField(default=0)),
                ('Cairo_ER', models.IntegerField(default=0)),
                ('Cairo_HU', models.IntegerField(default=0)),
                ('Delta_ER', models.IntegerField(default=0)),
                ('Delta_HU', models.IntegerField(default=0)),
                ('Giza_ER', models.IntegerField(default=0)),
                ('Giza_HU', models.IntegerField(default=0)),
                ('Canal_HU', models.IntegerField(default=0)),
                ('Upper_HU', models.IntegerField(default=0)),
                ('G_Cairo_ER', models.IntegerField(default=0)),
                ('G_Cairo_HU', models.IntegerField(default=0)),
                ('Total_Upper_HU', models.IntegerField(default=0)),
                ('Total_ER', models.IntegerField(default=0)),
                ('Total_HU', models.IntegerField(default=0)),
                ('Total_plans_V3', models.IntegerField(default=0)),
                ('Integ_Weights', models.IntegerField(default=0)),
                ('Total_ER_weighted', models.IntegerField(default=0)),
                ('Total_HU_weighted', models.IntegerField(default=0)),
                ('Total_Weighted_V3', models.IntegerField(default=0)),
                ('Start_date', models.DateField(default=datetime.date(2020, 4, 1))),
                ('End_date', models.DateField(default=datetime.date(2021, 3, 31))),
                ('Stream_life_time', models.IntegerField(default=12)),
                ('tp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_plan.tp_name')),
            ],
        ),
        migrations.CreateModel(
            name='region_phasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_plan.tp_details')),
            ],
        ),
        migrations.CreateModel(
            name='assumption_phasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_plan.tp_details')),
            ],
        ),
        migrations.CreateModel(
            name='acheived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_plan.tp_details')),
            ],
        ),
    ]
