# Generated by Django 3.1.4 on 2020-12-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('site_id', models.CharField(max_length=30)),
                ('consultant_name', models.CharField(blank=True, max_length=30, null=True)),
                ('requester_dept', models.CharField(blank=True, max_length=30, null=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('new_requirement', models.TextField(blank=True, null=True)),
                ('last_visit', models.DateField(blank=True, default='', null=True)),
                ('status', models.CharField(blank=True, choices=[('in-progress', 'in-progress'), ('done', 'done')], max_length=30, null=True)),
                ('feedback', models.DateField(blank=True, default='', null=True)),
                ('requester', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('mail_name', models.CharField(blank=True, max_length=30, null=True)),
                ('project_name', models.CharField(blank=True, max_length=30, null=True)),
                ('site_case', models.CharField(blank=True, max_length=30, null=True)),
                ('building', models.CharField(blank=True, max_length=30, null=True)),
                ('max_rating_in', models.CharField(blank=True, max_length=30, null=True)),
                ('max_rating_per', models.CharField(blank=True, max_length=30, null=True)),
                ('consultant_recommendations', models.CharField(blank=True, max_length=30, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=30, null=True)),
                ('star_site', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=30, null=True)),
                ('last_modfied_date', models.DateTimeField(auto_now=True)),
                ('last_modfied_user', models.CharField(blank=True, max_length=30, null=True)),
                ('in_progress_date', models.CharField(blank=True, max_length=30, null=True)),
                ('done_date', models.CharField(blank=True, max_length=30, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('site_type', models.CharField(blank=True, max_length=30, null=True)),
                ('structure_type', models.CharField(blank=True, max_length=30, null=True)),
                ('height', models.CharField(blank=True, max_length=30, null=True)),
                ('wo_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
