# Generated by Django 3.1.4 on 2020-12-30 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Regional_operation', 'Regional_Operations'), ('radio', 'Radio'), ('service_management', 'service_management')], max_length=30, null=True)),
                ('sub_dep', models.CharField(choices=[('Cairo', 'Cairo_Region'), ('Giza', 'Giza_Region'), ('Delta', 'Delta_Region'), ('Alexandria', 'Alexandria_Region'), ('Upper-Red Sea and Sinai', 'Upper_Region'), ('governance', 'Govrernance'), ('Acceptance', 'Acceptance'), ('Giza_Alex_Region', 'Giza_Alex_Region'), ('Regional_operation', 'Regional_Operations')], max_length=30, null=True)),
                ('user_region', models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Delta', 'Delta'), ('Alexandria', 'Alexandria'), ('Upper-Red Sea and Sinai', 'Upper-Red Sea and Sinai'), ('Giza_Alex_Region', 'Giza_Alex_Region'), ('All', 'All')], max_length=30, null=True)),
                ('team', models.CharField(choices=[('Implementation', 'Implementation'), ('Rollout', 'Rollout'), ('Development', 'Development'), ('Environmental', 'Environmental'), ('SiteMnanagement', 'SiteMnanagement'), ('Cairo', 'Cairo_Region'), ('Giza', 'Giza_Region'), ('Delta', 'Delta_Region'), ('Alexandria', 'Alexandria_Region'), ('Upper-Red Sea and Sinai', 'Upper_Region'), ('governance', 'Govrernance'), ('Acceptance', 'Acceptance'), ('Giza_Alex_Region', 'Giza_Alex_Region'), ('Regional_operation', 'Regional_Operations')], max_length=30, null=True)),
                ('admin', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='ropf_auth/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pki', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('site_history', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('contract_renegotiation', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('site_continuity_risk', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('dashboard', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('query', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('technical_Plan', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('integration_Quota', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('smart_check_list', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('contractor_evaluation', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('contractor_allocation', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('field_planning', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('rca_acceptance', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('rca_nfm', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('civil_technical_office', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('unified_pwr_db', models.CharField(choices=[('r', 'r'), ('cr', 'cr'), ('cru', 'cru'), ('crud', 'crud'), ('no', 'no')], default='no', max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
