# Generated by Django 3.1.4 on 2020-12-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cluster_average',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=30)),
                ('cl_avg_key', models.CharField(max_length=70)),
                ('cl_avg_rent', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='site_management_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=30)),
                ('Last_Rent', models.FloatField(blank=True, default=None, null=True)),
                ('System_Start_Date', models.DateField(blank=True, null=True)),
                ('System_End_Date', models.DateField(blank=True, null=True)),
                ('Calc_From', models.DateField(blank=True, null=True)),
                ('Calc_To', models.DateField(blank=True, null=True)),
                ('Access_Status', models.CharField(max_length=30)),
                ('problematic_owner', models.CharField(max_length=30)),
                ('health_safety', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True)),
                ('tech_issue', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True)),
                ('remove_order', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True)),
                ('legal', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True)),
            ],
        ),
    ]
